### ISSUE TITLE
Why does the pipeline extract reads from a BAM to map them again?

### ISSUE THREAD

**Issue by hoelzer** [valegale/ONT_methylation#4]
Hey, 

While restructuring the pipeline code, I saw that your current inputs are BAM files, and then you extract the reads to map them again with `minimap2`—why? There is probably some good reason for that.

We will probably anyway provide more input options in the future, such as POD5 (adding a `Dorado` process) or FASTQ (and then directly doing the `minimap2` mapping, etc...)

**Comment by valegale** [comment]
In this way the fastq files are aligned with the reference (they are keeping the information regarding the methylation with the tag -T MM,ML) and then they are passed to modkit when they are aligned

**Comment by hoelzer** [comment]
Ahhh I forgot that the BAM you are using as input is just the Dorado output, right? So actually the BAM your pipeline gets as input is not aligned to the reference, right? 

If so, please feel free to close this issue : )

**Comment by valegale** [comment]
yep! I am going to write this in the readme
